services:
  traefik:
    image: "traefik:v2.9"
    init: true
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - base

  website:
    image: "optical"
    init: true
    container_name: "optical-website"
    ports:
      - "9090:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`website.docker.localhost`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.docker.network=base"
      - "traefik.http.website.loadbalancer.server.port=8082"
    networks:
      - base

networks:
  base:
    name: web-network
    driver: bridge